spring:
  application:
    name: skill-tracker-search

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: FSE4
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


  server:
    port: 8090
